var goodData = {
    path:[
        {
            title:"手机、数码、通讯",
            url:"###"
        },
        {
            title:"手机",
            url:"###"
        },
        {
            title:"小米手机",
            url:"###"
        },
        {
            title:"小米6 钉子户"
        }
    ],
    imagessrc:[
        {b:"./images/b1.png",s:"./images/s1.png"},
        {b:"./images/b2.png",s:"./images/s2.png"},
        {b:"./images/b3.png",s:"./images/s3.png"},
        {b:"./images/b4.png",s:"./images/s4.png"},
        {b:"./images/b5.png",s:"./images/s5.png"},
        {b:"./images/b6.png",s:"./images/s6.png"},
        {b:"./images/b1.png",s:"./images/s1.png"},
        {b:"./images/b2.png",s:"./images/s2.png"},
        {b:"./images/b3.png",s:"./images/s3.png"},
        {b:"./images/b4.png",s:"./images/s4.png"},
        {b:"./images/b5.png",s:"./images/s5.png"},
        {b:"./images/b6.png",s:"./images/s6.png"},
    ],
    goodsDetail:{
        title:"Redmi K60 12G银白色 移动联通电信5G手机",
        recommend:"推荐选择下方[移动优惠购],手机套餐全搞定",
        price:4399,
        promoteSales:{
            type:"加价购",
            content:"满999.00另加20.00元,或满1999另加30.00元,或满2999.00另加400.00元，即可在购物车购买促销商品",
        },
        support:"以旧换新,闲置手机回收,5G套餐超值抢,礼品购",
        address:"广东省 广州市 天河区",
        evaluateNum:100000,
        crumbData:[
            {
                "title":"选择颜色",
                "data":[
                    {
                        type:"金色",
                        changePrice:0
                    },
                    {
                        type:"银色",
                        changePrice:90
                    },
                    {
                        type:"黑色",
                        changePrice:60
                    }
                ]
            },
            {
                "title":"内容容量",
                "data":[
                    {
                        type:"16GB",
                        changePrice:0
                    },
                    {
                        type:"32GB",
                        changePrice:100
                    },
                    {
                        type:"64GB",
                        changePrice:200
                    },
                    {
                        type:"128GB",
                        changePrice:300
                    }
                ]
            },
            {
                "title":"选择版本",
                "data":[
                    {
                        type:"公开版",
                        changePrice:0
                    },
                    {
                        type:"移动版",
                        changePrice:-500
                    }
                ]
            },
            {
                "title":"购买方式",
                "data":[
                    {
                        type:"官方标配",
                        changePrice:0
                    },
                    {
                        type:"优惠移动版",
                        changePrice:-400
                    },
                    {
                        type:"电信优惠版",
                        changePrice:-410
                    }
                ]
            }
        ]
    }
}